
source 'https://github.com/CocoaPods/Specs.git'

workspace 'RAMUtilDemo.xcworkspace'

project 'RAMUtilDemo.xcodeproj'

target 'RAMUtilDemo' do
    platform :ios, '12.0'
    pod 'RAMUtil', :path => '../'  #:git => 'https://github.com/RamboQiu/RAMUtil.git', :tag => '1.0.0'
    pod 'YYKit'
    pod 'MLeaksFinder', :path => '/Users/rambo/Documents/MyProject/objcio/MLeaksFinder'
    pod 'FBRetainCycleDetector'
    pod "Apollo", :path => '/Users/rambo/Documents/MyProject/objcio/apollo-ios', :subspecs=>['SQLite', 'WebSocket'], :tag => 'v0.3.0' # :git => 'https://github.com/apollographql/apollo-ios.git'
end

#  platform :ios, '8.0'
#  project 'RAMRuntime-objc4-750.1/objc.xcodeproj'
#  end
